### ISSUE TITLE
Pre-Release Usage

### ISSUE THREAD

**Issue by tyrauber** [maplibre/maplibre-react-native#261]
## Motivation

It is really difficult to test new branches.  

In order to use the library, node_modules must be installed and `yarn build:plugin` and `yarn generate` must be run.  The build directories and files aren't committed, so the library can't be installed from Github.  The only way to test branches is to clone the repo, checkout the branch, install the dependencies and run the build scripts. 

Unfortunately, this prevents using branches with build services like EAS or CI, or building locally with`eas build --local`.

Being able to install branches from github would make it much easier to test changes. For example:

```
    "@maplibre/maplibre-react-native": "git://github.com/tyrauber/maplibre-react-native#feat/update-maplibre-native-version",
```

## Design Alternatives

As I see it there are two options:

- include the build files
- have github actions build and tag releases

The second option is probably best because it prevents developers from forgetting to build the library before committing.

### Implementation

Something like this should build and tag releases with semvar, branch name and sha.

```
name: Build and Release

on:
  push:
    branches:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '17'

    - name: Install Dependencies
      run: npm install

    - name: Extract Version from package.json
      id: extract_version
      run: echo "::set-output name=version::$(node -pe "require('./package.json').version")"

    - name: Run Build Scripts
      run: npm run build:plugin && npm run 

    - name: Commit Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Build and Release updates [skip ci]"


    - name: Get Branch Name
      id: branch_name
      run: echo "::set-output name=branch::$(echo $GITHUB_REF | awk -F/ '{print $3}')"

    - name: Get Commit SHA
      id: commit_sha
      run: echo "::set-output name=sha::${GITHUB_SHA::8}"

    - name: Tag Release
      run: |
        git tag -a "${{ steps.extract_version.outputs.version }}-${{ steps.branch_name.outputs.branch }}-${{ steps.commit_sha.outputs.sha }}" -m "Version ${{ steps.extract_version.outputs.version }} for branch ${{ steps.branch_name.outputs.branch }} (commit ${{ steps.commit_sha.outputs.sha }})"
        git push origin --tags

    - name: Push Changes
      run: git push
```
